---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ceph
  namespace: gb5
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-ceph-hdd-gz1
