---

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: gb5
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: redmine.foo.bar 
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: redmine-service
            port:
              number: 8080
