---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine
  namespace: gb5
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: redmine
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
      - name: redmine
        image: redmine:4.1.1
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef:
              name: redmine-configmap
        env:
          - name: REDMINE_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret
                key: password
          - name: REDMINE_SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: secret
                key: redminesecret

