---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    app: kubedoom
  name: my-kubedoom
  namespace: kubedoom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubedoom
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: kubedoom
    spec:
      containers:
      - image: storaxdev/kubedoom:0.5.0
        name: kubedoom
        ports:
          - containerPort: 5900
            protocol: TCP
      hostNetwork: true
      serviceAccountName: kubedoom

